### ISSUE TITLE
Intermitencia no calculo de Dano ao mudar o Status Terado

### ISSUE THREAD

**Issue by csalexsander** [robsonbittencourt/vgc-multicalc#1]
Encontrei uma intermitencia no calculo de dano, quando o TERA e setado false e depois true.

No caso caso abaixo, a Ursaluna consegue dar OHKO na FlutterMane

![image](https://github.com/robsonbittencourt/vgc-multicalc/assets/8169415/c5d643bf-f8c9-4137-a839-c002059672ed)

![image](https://github.com/robsonbittencourt/vgc-multicalc/assets/8169415/04417858-7445-445c-93d5-7b2f7d14aff1)

Ao desmarcar o TERA, e marcar novamente, o novo calculo sugere que a FlutterMane morre em 2HKO e não mais em OHKO, como anterioremente.

![image](https://github.com/robsonbittencourt/vgc-multicalc/assets/8169415/24c97880-6df7-44d9-9864-6d699ceb2523)

![image](https://github.com/robsonbittencourt/vgc-multicalc/assets/8169415/df581d31-a27c-4efa-9e9b-fe3120a2d480)

A unica forma de corrigir essa indicação errada, e clicando no pokemon atacante ao lado, ou no select pokemon, e voltar a clicar na Ursaluna, para que ele carregue o valor corretamente.

Outro detalhe, e que a funcionalidade de compartilhar o calculo não esta funcionando corretamente.

https://vgcmulticalc.com/data/20e76452-837c-4aaf-a587-d5255a51b946

**Comment by robsonbittencourt** [comment]
@csalexsander muito obrigado por indicar o problema. 

Eu tentei simular mas não consegui, você poderia me indicar o passo a passo que você fez por favor?

Outra dúvida, como você conseguiu selecionar todos os Pokémon da parte de baixo? Eu acredito que isso seja parte do problema hehe. Nessa tela, estando os defenders embaixo, era para ser possível selecionar somente um por vez, para ativar a edição.

**Comment by csalexsander** [comment]
Sobre como selecionar todos os pokemons la embaixo: Quando você cria, automaticamente ele seleciona.

Sobre o tirar o tera e colocar creio que encontrei o problema. A Ability da Ursaluna, esta sendo desconsiderada quando tera e destera, assim como quando troca a ability.

Veja abaixo o texto acima da raging bolt.

Normal com o tera
![image](https://github.com/robsonbittencourt/vgc-multicalc/assets/8169415/d7b8474b-f3cc-4519-a9d6-ca4da705d129)

Ao tirar o tera, a ability sai junto
![image](https://github.com/robsonbittencourt/vgc-multicalc/assets/8169415/2aeb4b91-2237-4106-85ed-bba0072a4e1d)

Como deveria ser com a ability e sem o tera
![image](https://github.com/robsonbittencourt/vgc-multicalc/assets/8169415/dfa8d5f4-cbeb-41d2-9c31-4996dc5b7165)

Como fica depois que eu tero novamente, ele continua não considerando a ability
![image](https://github.com/robsonbittencourt/vgc-multicalc/assets/8169415/60b275ec-0577-49f9-8c8a-fca9185a4784)

**Comment by robsonbittencourt** [comment]
@csalexsander mais uma vez muito obrigado pelo report. 

Corrigi 3 coisas aqui na issue:

1 - O bug em si que você reportou no Tera/Ability da Ursaluna
2 - Não mantém o Pokémon anterior selecionado ao criar um novo. Só deve haver um ativo nos defenders neste modo Many x Team.
3 - Corrigi o seu link de compartilhamento, se quiser tentar abrir ele novamente. Corrigi no código também para isso não acontecer mais.

Quando puder testar novamente por favor. Vou deixar a issue aberta enquanto isso. Valeu!

**Comment by csalexsander** [comment]
Boa corrigiu aqui. Valeu demais.

No caso o modo era Team Vs Many kk. Porem acho interessante poder ter pelo menos 2 pokemons adversarios ativos em campo dando golpe, pra gente conseguir simular um dano dobrado X em cima de certo pokemon, pra saber se aguenta ou não.

**Comment by robsonbittencourt** [comment]
@csalexsander desculpa, eu comentei errado. 

2 - Não mantém o Pokémon anterior selecionado ao criar um novo. Só deve haver um ativo nos defenders neste modo **Team x Many**.

Segue podendo selecionar 2 pokes no Many x Team 😄. 

Mais uma vez obrigado pela ajuda, e qualquer coisa só abrir uma issue ou me mandar uma mensagem.
