### ISSUE TITLE
Flame Orb does not activate

### ISSUE THREAD

**Issue by sharkwouter** [robsonbittencourt/vgc-multicalc#4]
Hey, thanks for creating this project, it is really cool and works well. I did find a missing feature. When I throw in Ursaluna with Guts and Flame Orb with 252 attack EVs and an adamant nature, it will tell me that Fascade will only KO Sneasler and Tatsugiri. Here is an image of it: 
![Screenshot from 2024-11-15 11-46-55](https://github.com/user-attachments/assets/ef1237b7-34e1-4b45-8d3e-24ee1dcb353a)

This makes me assume that the burn is not applied. I did not find a way to activate it. So this could be either a missing feature or a UX issue.

**Comment by robsonbittencourt** [comment]
Hi @sharkwouter. Sorry for delay I missed the issue notification.

At the top of the Pokémon editor, you can change Ursaluna's status condition as shown in the image.

If you still have any problems with the calculation, please include another printout of the top part, as this will help us investigate.

Thank you very much for your feedback, and I'm glad the project is being useful to you.


![2024-12-05_22-44](https://github.com/user-attachments/assets/71271081-91e5-4179-852a-beadeebcead1)

**Comment by sharkwouter** [comment]
Oh, I missed that. Thanks for answering. Will take a look.
